"use client";
import {useEffect,useMemo,useState} from "react"; import "./style.css";
async function hash(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
const SOURCE="https://vitalik.eth.limo/general/2026/09/27/the_cryptographic_world_computer.html",MINT="8ZMUvzUfmPvREhVRN156nwX5HoNmeUHDR3niJg6gpump",PUMP=`https://pump.fun/coin/${MINT}`,RPC="https://api.mainnet-beta.solana.com";
const DEMOS={AI:{icon:"✦",name:"AI SWARM",title:"ASK THE PLANET TO THINK",desc:"One hard AI task. Eight independent workers. One cryptographic receipt.",task:"Analyze 100,000 blockchain transactions and find suspicious patterns.",xp:120},PRIVATE:{icon:"◉",name:"PRIVATE COMPUTE",title:"COMPUTE ON SECRETS",desc:"Prove a fact about sensitive data without making the raw data public.",task:"Prove this private dataset passes the compliance rule without revealing the dataset.",xp:180},SCIENCE:{icon:"⌬",name:"SCIENCE GRID",title:"MAKE EARTH ONE MACHINE",desc:"Split enormous scientific work into independently verifiable compute chunks.",task:"Split a protein-folding simulation into 8 independently verifiable compute chunks.",xp:250}};
const WORKERS=["TOKYO","SINGAPORE","BERLIN","LONDON","NEW YORK","SÃO PAULO","SYDNEY","MOON-01"];
const RARITY={COMMON:{mult:1,icon:"◆"},RARE:{mult:1.5,icon:"✦"},EPIC:{mult:2.5,icon:"✧"},LEGENDARY:{mult:5,icon:"★"}};
function rarityFrom(h){const n=parseInt(h.slice(0,8),16)%1000;return n<12?"LEGENDARY":n<90?"EPIC":n<300?"RARE":"COMMON"}
async function getWorldBalance(owner){try{const r=await fetch(RPC,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method:"getTokenAccountsByOwner",params:[owner,{mint:MINT},{encoding:"jsonParsed"}]})});const j=await r.json();return(j.result?.value||[]).reduce((a,x)=>a+Number(x.account.data.parsed.info.tokenAmount.uiAmount||0),0)}catch{return null}}
export default function Home(){const[wallet,setWallet]=useState(""),[balance,setBalance]=useState(null),[kind,setKind]=useState("AI"),[task,setTask]=useState(DEMOS.AI.task),[running,setRunning]=useState(false),[stage,setStage]=useState(0),[jobs,setJobs]=useState([]),[last,setLast]=useState(null);useEffect(()=>{try{setJobs(JSON.parse(localStorage.getItem("world-game-jobs")||"[]"))}catch{}},[]);const xp=useMemo(()=>Math.round(jobs.reduce((a,j)=>a+(j.xp||0),0)),[jobs]),completed=useMemo(()=>new Set(jobs.map(j=>j.kind)),[jobs]),level=Math.floor(xp/500)+1,nodeUnlocked=completed.size===3;
async function connect(){const p=window.solana;if(!p?.isPhantom){window.open("https://phantom.com","_blank");return}try{const r=await p.connect(),w=r.publicKey.toString();setWallet(w);setBalance(await getWorldBalance(w))}catch{}}
function select(k){setKind(k);setTask(DEMOS[k].task);setStage(0);setLast(null)}
async function launch(){if(running||!task.trim())return;setRunning(true);setLast(null);for(let s=1;s<=4;s++){setStage(s);await new Promise(r=>setTimeout(r,s===2?1100:650))}const nonce=crypto.randomUUID(),receipt=await hash(`${kind}|${task}|${nonce}|${wallet||"guest"}`),rarity=rarityFrom(receipt),node=WORKERS[parseInt(receipt.slice(8,10),16)%WORKERS.length],base=DEMOS[kind].xp,gain=Math.round(base*RARITY[rarity].mult),j={id:nonce,kind,task,receipt,rarity,node,xp:gain,at:new Date().toISOString(),workers:8,proof:jobs.length+1,holder:Number(balance||0)>0};const n=[j,...jobs].slice(0,50);setJobs(n);setLast(j);localStorage.setItem("world-game-jobs",JSON.stringify(n));setRunning(false)}
function share(){if(!last)return;const text=`${RARITY[last.rarity].icon} I pulled a ${last.rarity} WORLD GENESIS PROOF #${String(last.proof).padStart(6,"0")}\n\nNODE: ${last.node}\nMISSION: ${DEMOS[last.kind].name}\n+${last.xp} XP\n\nThe world computed. Cryptography proved it.\n\n$WORLD`;window.open(`https://x.com/intent/post?text=${encodeURIComponent(text)}&url=${encodeURIComponent(location.origin)}`,"_blank")}
return <main><div className="noise"/><nav><div className="brand"><span>W</span><b>WORLD COMPUTER</b><i>α</i></div><div className="navright"><a href="#origin">ORIGIN</a><a href="#genesis">PLAY</a><span className="tokenBal">LV.{level} · {xp} XP</span>{wallet&&<span className="tokenBal">{balance===null?"…":balance.toLocaleString(undefined,{maximumFractionDigits:2})} WORLD</span>}<a className="buyTop" href={PUMP} target="_blank">$WORLD ↗</a><button onClick={connect}>{wallet?wallet.slice(0,4)+"…"+wallet.slice(-4):"CONNECT"}</button></div></nav>
<section className="mega"><div className="stars"/><div className="megaCopy"><div className="signal"><i/> GENESIS SEASON · 500 PROOFS</div><h1>THE<br/>WORLD<br/><em>COMPUTES.</em></h1><p>Enter the Genesis game. Run cryptographic compute missions. Hunt rare proofs. Complete all three protocols. Become a WORLD NODE.</p><div className="megaBtns"><a href="#genesis">ENTER GENESIS ↓</a><a className="ghost" href={SOURCE} target="_blank">VITALIK'S IDEA ↗</a></div><div className="contract"><span>$WORLD / SOLANA</span><code>{MINT}</code><button onClick={()=>navigator.clipboard?.writeText(MINT)}>COPY</button></div></div><div className="orbital"><div className="halo h1"/><div className="halo h2"/><div className="earth"><span>W</span></div>{WORKERS.map((w,i)=><div className={`sat sat${i}`} key={w}><i/>{w}</div>)}</div><div className="vertical">HUNT PROOFS · BUILD XP · BECOME A NODE</div></section>
<section className="ticker"><span>500 GENESIS SLOTS</span><i>✦</i><span>4 RARITIES</span><i>✦</i><span>3 MISSIONS</span><i>✦</i><span>8 WORLD NODES</span><i>✦</i><span>1 PROTOCOL</span></section>
<section id="origin" className="origin"><div className="sectionNum">001 / ORIGIN</div><div className="originGrid"><div className="quote"><small>VITALIK BUTERIN · SEPTEMBER 27 2026</small><h2>“THE CRYPTOGRAPHIC<br/>WORLD COMPUTER”</h2><p>Computation can happen in many places while cryptography makes the result verifiable. We turned that idea into a playable experiment.</p><a href={SOURCE} target="_blank">READ THE ORIGINAL ↗</a></div><div className="build"><small>THE GAME LOOP</small><b>RUN.<br/>PROVE.<br/>COLLECT.</b><div className="buildFlow"><span>MISSION</span><i>→</i><span>PROOF</span><i>→</i><strong>RARITY</strong></div></div></div></section>
<section id="genesis" className="demo"><div className="sectionNum">002 / GENESIS ARENA</div><div className="demoHead"><div><small>WORLD GENESIS GAME</small><h2>HUNT THE<br/><em>LEGENDARY.</em></h2></div><div className="genCounter"><span>YOUR GENESIS RUN</span><b>{String(jobs.length).padStart(3,"0")} <i>/ 500 prototype</i></b><div><i style={{width:`${Math.min(100,jobs.length/5)}%`}}/></div><small>Global 500-wallet registry is the next onchain step.</small></div></div>
<div className="gamebar"><div><small>LEVEL</small><b>{level}</b></div><div><small>XP</small><b>{xp}</b></div><div><small>MISSIONS</small><b>{completed.size}/3</b></div><div><small>WORLD NODE</small><b className={nodeUnlocked?"green":""}>{nodeUnlocked?"UNLOCKED":"LOCKED"}</b></div></div>
<div className="rarities"><span>DROP RATES</span><b>◆ COMMON 70%</b><b>✦ RARE 21%</b><b>✧ EPIC 7.8%</b><b>★ LEGENDARY 1.2%</b></div>
<div className="cards">{Object.entries(DEMOS).map(([k,d])=><button key={k} onClick={()=>select(k)} className={kind===k?"card active":"card"}><span className="icon">{completed.has(k)?"✓":d.icon}</span><small>{d.name} · +{d.xp} BASE XP</small><b>{d.title}</b><p>{d.desc}</p><i>{completed.has(k)?"MISSION CLEARED · RUN AGAIN":"SELECT MISSION →"}</i></button>)}</div>
<div className="terminal"><div className="prompt"><div className="termTop"><span>MISSION://{kind.toLowerCase()}</span><i>{running?"COMPUTING":"ARMED"}</i></div><textarea value={task} onChange={e=>setTask(e.target.value)}/><button className="launch" onClick={launch} disabled={running}>{running?`0${stage}/04 · ${stage===1?"SPLITTING":stage===2?"WORLD COMPUTING":stage===3?"ROLLING PROOF":"VERIFYING"}…`:"RUN MISSION + ROLL PROOF →"}</button></div><div className="world"><div className={`globe ${running?"running":""}`}><div className="core"><span>W</span><b>{running?stage<3?"COMPUTING":"PROVING":last?last.rarity:"STANDBY"}</b></div>{WORKERS.map((w,i)=><div key={w} className={`node n${i} ${running&&stage>=2?"pulse":""}`}><i/><span>{w}</span></div>)}</div><div className="worldStatus"><span>WORKERS</span><b>08</b><span>DROP</span><b>{last?last.rarity:"?"}</b><span>NODE</span><b>{last?last.node:"?"}</b></div></div></div>
<div className="pipeline"><div className={stage>=1?"on":""}><b>01</b><span>SPLIT</span></div><i>→</i><div className={stage>=2?"on":""}><b>02</b><span>COMPUTE</span></div><i>→</i><div className={stage>=3?"on":""}><b>03</b><span>ROLL</span></div><i>→</i><div className={stage>=4?"on":""}><b>04</b><span>VERIFY</span></div></div>
{last&&<div className={`proofCard rarity-${last.rarity.toLowerCase()}`}><div className="proofSeal">{RARITY[last.rarity].icon}</div><div className="proofCopy"><small>WORLD GENESIS PASSPORT · {last.rarity}</small><h3>#{String(last.proof).padStart(6,"0")}</h3><p>{last.node} NODE · {DEMOS[last.kind].name} · +{last.xp} XP {last.holder?"· WORLD HOLDER":""}</p><code>{last.receipt}</code><span>PROTOTYPE GENESIS PROOF · CRYPTOGRAPHIC RECEIPT GENERATED LOCALLY</span></div><button onClick={share}>FLEX ON X ↗</button></div>}
<div className="quest"><div><small>META QUEST</small><h3>ACTIVATE A WORLD NODE</h3><p>Clear all three mission classes to unlock your WORLD NODE status.</p></div>{Object.keys(DEMOS).map(k=><span key={k} className={completed.has(k)?"done":""}>{completed.has(k)?"✓":"○"} {DEMOS[k].name}</span>)}<b>{nodeUnlocked?"NODE ACTIVE":"COMPLETE 3/3"}</b></div></section>
<section className="vision"><div className="sectionNum">003 / WHY PLAY</div><h2>PROOF<br/>BECOMES<br/><em>STATUS.</em></h2><div className="versus"><div><small>NORMAL TOKEN LAUNCH</small><b>BUY.<br/>WAIT.<br/>WATCH CHART.</b></div><span>→</span><div className="future"><small>WORLD GENESIS</small><b>PLAY.<br/>PROVE.<br/>COLLECT.</b></div></div></section>
<section className="possibilities"><div className="sectionNum">004 / GENESIS CLASSES</div><div className="endTitle"><h2>EVERY PROOF<br/>HAS A <em>STORY.</em></h2><p>Mission, node, rarity, XP and receipt combine into a unique Genesis Passport. The rarest proofs are deterministic from the receipt — not manually assigned.</p></div><div className="biggrid"><div><span>◆ 70%</span><b>COMMON</b><p>The backbone of the World Computer.</p></div><div><span>✦ 21%</span><b>RARE</b><p>1.5× XP. A harder proof pull.</p></div><div><span>✧ 7.8%</span><b>EPIC</b><p>2.5× XP. Built to flex.</p></div><div className="worldTile"><span>★ 1.2%</span><b>LEGENDARY</b><p>5× XP. The Genesis chase.</p><a href={PUMP} target="_blank">VIEW $WORLD ↗</a></div></div></section>
<section className="token"><div className="tokenOrb">W</div><div><small>$WORLD · LIVE ON SOLANA</small><h2>PLAY FIRST.<br/>TOKEN SECOND.</h2><p>The token is live. The game currently awards XP and local Genesis Proofs, not real token payouts. Connect Phantom to display your actual $WORLD balance.</p><div className="tokenActions"><a href={PUMP} target="_blank">VIEW $WORLD ↗</a><button onClick={()=>navigator.clipboard?.writeText(MINT)}>COPY CONTRACT</button></div></div></section><footer><div><b>W</b> WORLD COMPUTER α</div><span>Independent experimental prototype. Genesis numbering is local until the shared registry ships. Compute workers and XP are simulated; $WORLD is a live Solana token.</span></footer></main>}
