"use client";
import {useEffect,useMemo,useState} from "react"; import "./style.css";
async function hash(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
const MODES={HASH:{label:"HASH PROOF",reward:2.5,desc:"Commit any data to a deterministic SHA-256 receipt."},AI:{label:"AI JOB",reward:8,desc:"Create a receipt for an offchain AI inference job."},DATA:{label:"DATA PROOF",reward:5,desc:"Timestamp a dataset or result with a reproducible fingerprint."}};
export default function Home(){
 const [wallet,setWallet]=useState(""),[task,setTask]=useState("Prove this message existed: WORLD COMPUTER / 2026."),[jobs,setJobs]=useState([]),[busy,setBusy]=useState(false),[mode,setMode]=useState("HASH"),[credits,setCredits]=useState(100);
 useEffect(()=>{try{setJobs(JSON.parse(localStorage.getItem("worldjobs")||"[]"));setCredits(Number(localStorage.getItem("worldcredits")||100))}catch{}},[]);
 const earned=useMemo(()=>jobs.reduce((a,j)=>a+(j.reward||0),0),[jobs]);
 async function connect(){const p=window.solana;if(!p?.isPhantom){window.open("https://phantom.com","_blank");return}try{const r=await p.connect();setWallet(r.publicKey.toString())}catch{}}
 async function run(){if(!task.trim()||busy)return;setBusy(true);await new Promise(r=>setTimeout(r,650));const t=performance.now(),nonce=crypto.randomUUID(),receipt=await hash(`${mode}|${task.trim()}|${nonce}`),reward=MODES[mode].reward,j={id:nonce,mode,task:task.trim(),receipt,reward,ms:Math.max(1,Math.round(performance.now()-t)),at:new Date().toISOString(),wallet:wallet||"guest"};const n=[j,...jobs].slice(0,20),c=credits+reward;setJobs(n);setCredits(c);localStorage.setItem("worldjobs",JSON.stringify(n));localStorage.setItem("worldcredits",String(c));setBusy(false)}
 function copy(x){navigator.clipboard?.writeText(x)}
 return <main><nav><b>◇ WORLD COMPUTER <i>α</i></b><div className="navright"><span className="balance">{credits.toFixed(1)} <small>WORLD</small></span><button onClick={connect}>{wallet?wallet.slice(0,4)+"…"+wallet.slice(-4):"Connect Solana"}</button></div></nav>
 <section className="hero"><div className="eyebrow">CRYPTOGRAPHIC COMPUTE MARKET / SOLANA READY</div><h1>Compute anywhere.<br/><em>Verify everywhere.</em></h1><p>Turn offchain work into portable cryptographic receipts. Submit a job, verify its fingerprint, and simulate token rewards today — with SPL settlement ready to plug in next.</p>
 <div className="modes">{Object.entries(MODES).map(([k,v])=><button key={k} className={mode===k?"active":""} onClick={()=>setMode(k)}><b>{v.label}</b><span>+{v.reward} WORLD</span></button>)}</div>
 <div className="box"><div className="boxhead"><label>NEW {MODES[mode].label}</label><span>REWARD <b>+{MODES[mode].reward} WORLD</b></span></div><p className="hint">{MODES[mode].desc}</p><textarea value={task} onChange={e=>setTask(e.target.value)} placeholder="Describe the work to verify..."/><div className="runrow"><span>{wallet?"SOLANA IDENTITY ATTACHED":"GUEST MODE · CONNECT SOLANA FOR IDENTITY"}</span><button className="run" onClick={run} disabled={busy}>{busy?"GENERATING PROOF…":"RUN + EARN →"}</button></div></div></section>
 <section className="grid"><div><b>{jobs.length}</b><span>VERIFIED JOBS</span></div><div><b>{earned.toFixed(1)}</b><span>WORLD EARNED</span></div><div><b>SHA-256</b><span>PROOF LAYER</span></div><div><b className="green">● READY</b><span>SPL SETTLEMENT</span></div></section>
 <section className="flow"><div><small>01</small><b>SUBMIT</b><p>Offchain task</p></div><i>→</i><div><small>02</small><b>COMPUTE</b><p>Any worker</p></div><i>→</i><div><small>03</small><b>PROVE</b><p>Receipt</p></div><i>→</i><div><small>04</small><b>SETTLE</b><p>SPL token</p></div></section>
 <section className="log"><div className="loghead"><h2>PROOF EXPLORER</h2><span>{jobs.length} RECEIPTS</span></div>{!jobs.length&&<p className="muted">No proofs yet. Run the first job above.</p>}{jobs.map(j=><article key={j.id}><div className="articleTop"><strong>✓ VERIFIED · {MODES[j.mode||"HASH"].label}</strong><b>+{j.reward||0} WORLD</b></div><p>{j.task}</p><div className="receipt"><code>{j.receipt}</code><button onClick={()=>copy(j.receipt)}>COPY</button></div><small>{j.ms} ms · {j.wallet==="guest"?"guest":j.wallet.slice(0,10)+"…"} · {new Date(j.at).toLocaleString()}</small></article>)}</section>
 <section className="token"><div><div className="eyebrow">TOKEN LAYER</div><h2>WORLD powers the compute market.</h2><p>This prototype uses simulated WORLD credits. A real SPL mint can later replace the local balance for job fees, worker rewards, staking and proof-market incentives without changing the user flow.</p></div><div className="coin">W</div></section>
 <footer>WORLD COMPUTER · EXPERIMENTAL PROTOTYPE · SIMULATED CREDITS HAVE NO MONETARY VALUE</footer></main>}
