"use client";
import {useEffect,useMemo,useState} from "react"; import "./style.css";
async function hash(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
const DEMOS={AI:{icon:"✦",name:"AI SWARM",title:"Ask 8 AI workers at once",desc:"Split one hard AI task across independent workers, combine the result, then create a cryptographic receipt.",task:"Analyze 100,000 blockchain transactions and find suspicious patterns."},PRIVATE:{icon:"◉",name:"PRIVATE COMPUTE",title:"Compute without exposing the secret",desc:"A future privacy lane for proving facts about sensitive data without publishing the underlying data.",task:"Prove this private dataset passes the compliance rule without revealing the dataset."},SCIENCE:{icon:"⌬",name:"SCIENCE GRID",title:"Turn the internet into a supercomputer",desc:"Break a huge simulation into chunks, let machines work in parallel, and verify the combined result.",task:"Split a protein-folding simulation into 8 independently verifiable compute chunks."}};
const WORKERS=["TOKYO","SINGAPORE","BERLIN","LONDON","NEW YORK","SÃO PAULO","SYDNEY","MOON-01"];
export default function Home(){
 const [wallet,setWallet]=useState(""),[kind,setKind]=useState("AI"),[task,setTask]=useState(DEMOS.AI.task),[running,setRunning]=useState(false),[stage,setStage]=useState(0),[jobs,setJobs]=useState([]),[last,setLast]=useState(null);
 useEffect(()=>{try{setJobs(JSON.parse(localStorage.getItem("world-v2-jobs")||"[]"))}catch{}},[]); const total=useMemo(()=>jobs.reduce((a,j)=>a+j.reward,0),[jobs]);
 async function connect(){const p=window.solana;if(!p?.isPhantom){window.open("https://phantom.com","_blank");return}try{const r=await p.connect();setWallet(r.publicKey.toString())}catch{}}
 function select(k){setKind(k);setTask(DEMOS[k].task);setStage(0);setLast(null)}
 async function launch(){if(running||!task.trim())return;setRunning(true);setLast(null);for(let s=1;s<=4;s++){setStage(s);await new Promise(r=>setTimeout(r,s===2?1250:800))}const nonce=crypto.randomUUID(),receipt=await hash(`${kind}|${task}|${nonce}`),reward=kind==="AI"?18:kind==="PRIVATE"?28:42,j={id:nonce,kind,task,receipt,reward,at:new Date().toISOString(),workers:8};const n=[j,...jobs].slice(0,12);setJobs(n);setLast(j);localStorage.setItem("world-v2-jobs",JSON.stringify(n));setRunning(false)}
 return <main><nav><div className="brand"><span>◇</span> WORLD COMPUTER <i>α</i></div><div className="navright"><span className="live"><i/> NETWORK LIVE</span><button onClick={connect}>{wallet?wallet.slice(0,4)+"…"+wallet.slice(-4):"CONNECT SOLANA"}</button></div></nav>
 <section className="hero"><div className="eyebrow">A CRYPTOGRAPHIC WORLD COMPUTER</div><h1>One job.<br/><em>The whole world computes.</em></h1><p className="lead">Instead of trusting one giant server, break work across machines everywhere — then use cryptography to prove the answer. <b>Try it below.</b></p><div className="heroStats"><span><b>8</b> workers</span><span><b>1</b> proof</span><span><b>0</b> trust required*</span></div></section>
 <section className="demo"><div className="demoTitle"><span>LIVE CONCEPT DEMO</span><b>Pick something impossible-looking ↓</b></div><div className="cards">{Object.entries(DEMOS).map(([k,d])=><button key={k} onClick={()=>select(k)} className={kind===k?"card active":"card"}><span className="icon">{d.icon}</span><small>{d.name}</small><b>{d.title}</b><p>{d.desc}</p></button>)}</div>
 <div className="machine"><div className="prompt"><div><small>YOUR JOB</small><b>{DEMOS[kind].name}</b></div><textarea value={task} onChange={e=>setTask(e.target.value)}/><button className="launch" onClick={launch} disabled={running}>{running?"WORLD IS COMPUTING…":"SEND TO THE WORLD →"}</button></div>
 <div className="world"><div className="globe"><div className="core">WORLD<br/><b>{running?stage<3?"COMPUTING":"PROVING":last?"VERIFIED":"READY"}</b></div>{WORKERS.map((w,i)=><div key={w} className={`node n${i} ${running&&stage>=2?"pulse":""}`}><i/>{w}</div>)}</div></div></div>
 <div className="pipeline"><div className={stage>=1?"on":""}><b>1</b><span>SPLIT</span><small>Job → 8 chunks</small></div><i>→</i><div className={stage>=2?"on":""}><b>2</b><span>COMPUTE</span><small>8 workers run</small></div><i>→</i><div className={stage>=3?"on":""}><b>3</b><span>PROVE</span><small>Cryptographic receipt</small></div><i>→</i><div className={stage>=4?"on":""}><b>4</b><span>SETTLE</span><small>Reward in WORLD</small></div></div>
 {last&&<div className="wow"><div className="seal">✓</div><div><small>CRYPTOGRAPHIC RECEIPT GENERATED</small><h2>THE RESULT IS VERIFIED.</h2><p>8 workers → 1 verifiable receipt → <b>+{last.reward} WORLD</b> simulated reward</p><code>{last.receipt}</code></div></div>}</section>
 <section className="simple"><div className="eyebrow">WHY THIS MATTERS</div><h2>Today you trust the computer.<br/><em>Tomorrow the computer proves itself.</em></h2><div className="compare"><div><small>TODAY</small><h3>“Trust our server.”</h3><p>One company computes the answer. You trust its infrastructure, logs and claims.</p></div><div className="arrow">→</div><div className="future"><small>WORLD COMPUTER</small><h3>“Verify the proof.”</h3><p>Anyone can compute. Cryptography becomes the trust layer between humans, AI agents and machines.</p></div></div></section>
 <section className="possibilities"><div className="eyebrow">WHAT THIS COULD BECOME</div><h2>A market for intelligence itself.</h2><div className="biggrid"><div><b>AI ↔ AI</b><p>Autonomous agents hire other machines to compute, verify and settle work.</p></div><div><b>PRIVATE AI</b><p>Ask questions about sensitive data without making the raw data public.</p></div><div><b>GLOBAL GPU</b><p>Idle computers become pieces of one permissionless supercomputer.</p></div><div><b>$WORLD</b><p>A future SPL token can pay workers, unlock jobs and settle verified computation.</p></div></div></section>
 <section className="explorer"><div className="explorerHead"><div><small>WORLD EXPLORER</small><h2>Verified jobs</h2></div><span>{jobs.length} jobs · {total} WORLD simulated</span></div>{!jobs.length?<p className="empty">Your first verified job will appear here.</p>:jobs.map(j=><article key={j.id}><div><strong>✓ VERIFIED</strong><b>{DEMOS[j.kind].name}</b></div><p>{j.task}</p><code>{j.receipt}</code><small>{j.workers} workers · +{j.reward} WORLD · {new Date(j.at).toLocaleString()}</small></article>)}</section>
 <section className="token"><div><div className="eyebrow">NEXT: REAL TOKEN</div><h2>$WORLD can turn the demo into an economy.</h2><p>Once a Solana mint is connected, the app can read real balances, gate premium jobs and route users into the real token ecosystem. Worker payouts shown today are simulated until onchain settlement is implemented.</p></div><div className="coin">W</div></section>
 <footer><b>WORLD COMPUTER</b><span>Inspired by the cryptographic world computer idea · Experimental prototype · *This demo visualizes the architecture; it is not yet a production ZK/FHE compute network.</span></footer></main>}
